### ISSUE TITLE
Uncaught error when using Rapids 24.12 due to pylibraft -> cuvs

### ISSUE THREAD

**Issue by praateekmahajan** [rapidsai/crossfit#102]
TLDR : `from pylibraft.neighbors.brute_force import knn` fails in 24.12 which is used in `from crossfit.backend.torch.op.vector_search import TorchExactSearch`.

------ 
The following code works fine in 24.10 but not in 24.12.

```python
import crossfit
import cudf
import torch
print(crossfit.convert_array(cudf.Series([[1,2,3]]), torch.Tensor))
```

This was debugged by using
```python
import crossfit
print("Available from_dlpack dispatches:", crossfit.data.array.conversion.dispatch_from_dlpack._lookup)
```
And in 24.10 we see the output is 

```
Available from_dlpack dispatches: {<class 'numpy.ndarray'>: <function np_from_dlpack at 0x7f0cfd9385e0>, <class 'torch.Tensor'>: <function torch_from_dlpack at 0x7f0b921ba4d0>}
```
while in 24.12 it is
```
Available from_dlpack dispatches: {<class 'numpy.ndarray'>: <function np_from_dlpack at 0x7faea9f615a0>}
```

This suggested that `torch_from_dlpack` is not being imported correctly, and then on further look when we just run 
```python
from crossfit.backend.torch.array import *
```
It fails in 24.12 due to `crossfit.backend.torch.__init__` not being resolved correctly

**Comment by VibhuJawa** [comment]
Closed by: https://github.com/rapidsai/crossfit/pull/103
