### ISSUE TITLE
[BUG] `ListColumn` construction breaks in cudf 24.10

### ISSUE THREAD

**Issue by praateekmahajan** [rapidsai/crossfit#84]
As a consequence of https://github.com/rapidsai/cudf/issues/16469 to align signatures of subclasses of `ColumnBase` the signature changed between 24.08 and 24.10 (which is yet not stable and accessible through nightly release). We need to modify how we construct ListColumn at the two places we 
1. https://github.com/rapidsai/crossfit/blob/69de99b9e13eb1fb5c51ed8eee5cc0607e664c92/crossfit/backend/cudf/series.py#L35-L42
2. https://github.com/rapidsai/crossfit/blob/69de99b9e13eb1fb5c51ed8eee5cc0607e664c92/crossfit/backend/cudf/series.py#L65-L77

### Before
https://github.com/rapidsai/cudf/blob/496151225aaf90318c089939d3a74e6ccee4e28d/python/cudf/cudf/core/column/lists.py#L39-L51

### After
https://github.com/rapidsai/cudf/blob/0b32f55b1ed38507437770d21da1e4e1a1c4a17d/python/cudf/cudf/core/column/lists.py#L41-L53

## Environment
```sh
> pip freeze | grep crossfit
crossfit @ git+https://github.com/rapidsai/crossfit.git@69de99b9e13eb1fb5c51ed8eee5cc0607e664c92

> pip freeze | grep cudf
cudf-cu12==24.10.0a309
dask-cudf-cu12==24.10.0a309
libcudf-cu12==24.10.0a309
pylibcudf-cu12==24.10.0a309
```

**Comment by VibhuJawa** [comment]
Thanks for catching this. 


We really need to fix https://github.com/rapidsai/cudf/issues/11130 to prevent future breakages. We were relying on internal API which does not hold stability guarantees.

**Comment by VibhuJawa** [comment]
Closed by: https://github.com/rapidsai/crossfit/pull/86
