### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by conceptofmind** [rapidsai/crossfit#85]
Hi all,

Can you please provide a bibtex citation or similar for this repository?

Thank you!

**Comment by VibhuJawa** [comment]
Let me ask internally how to cite this, sorry for the delay on this .

**Comment by conceptofmind** [comment]
> Let me ask internally how to cite this, sorry for the delay on this .

Thank you!

**Comment by VibhuJawa** [comment]
This is what you can use. 
```
@Manual{
              title = {RAPIDS: Libraries for End to End GPU Data Science},
              author = {RAPIDS Development Team},
              year = {2023},
              url = {https://rapids.ai}
            }
```

**Comment by conceptofmind** [comment]
> This is what you can use.
> 
> ```
> @Manual{
>               title = {RAPIDS: Libraries for End to End GPU Data Science},
>               author = {RAPIDS Development Team},
>               year = {2023},
>               url = {https://rapids.ai}
>             }
> ```

Perfect. Great.
